### ISSUE TITLE
[SUGGESTION] Translation support?

### ISSUE THREAD

**Issue by Blueberryy** [NubTheFatMan/Nubs-Safe-Zones#1]
You can use gmod localization system or made your own

**Comment by NubTheFatMan** [comment]
Aside from the fact that I'm not actively working on this, it wouldn't be too difficult. I could definitely add a translation _system_, but I couldn't add other languages myself. I only know English.

**Comment by Blueberryy** [comment]
> Aside from the fact that I'm not actively working on this, it wouldn't be too difficult. I could definitely add a translation _system_, but I couldn't add other languages myself. I only know English.

Add in description of addon text like this: "Do you want to help addon? You can translate it to your native language! *link here*"

**Comment by NubTheFatMan** [comment]
This is now in the process of being implemented

**Comment by Blueberryy** [comment]
> This is now in the process of being implemented

That's great to hear! I hope that you will add .txt translation file for workshop addon page too. (addon title and description)
