### ISSUE TITLE
[Bug] Can't delete zone's

### ISSUE THREAD

**Issue by SteveWasTakenTTV** [NubTheFatMan/Nubs-Safe-Zones#2]
Error when trying to delete zone's 

`[nubs-safe-zones-main] Warning! A net message (nsz_delete) is already started! Discarding in favor of the new message! (nsz_delete)
  1. unknown - addons/nubs-safe-zones-main/lua/nsz/client/concmds.lua:10
   2. unknown - lua/includes/modules/concommand.lua:54
`

**Comment by NubTheFatMan** [comment]
I see. You must be running the command too fast, I could add a timeout or queue system to fix this. Thank you for bringing this to my attention. I'm not actively working on this, but I do plan to revisit it

**Comment by sirhChristoph** [comment]
I know it's a bit late haha but thought I'd add this as you said you wanted to revisit:

] "nsz_delete"

[nubs_safe_zones-main] Warning! A net message (nsz_delete) is already started! Discarding in favor of the new message! (nsz_delete)
  1. unknown - addons/nubs_safe_zones-main/lua/nsz/client/concmds.lua:11
   2. unknown - lua/includes/modules/concommand.lua:54


[nubs_safe_zones-main] addons/nubs_safe_zones-main/lua/nsz/client/concmds.lua:12: bad argument #1 to 'WriteString' (string expected, got nil)
  1. WriteString - [C]:-1
   2. unknown - addons/nubs_safe_zones-main/lua/nsz/client/concmds.lua:12
    3. unknown - lua/includes/modules/concommand.lua:54
